version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/church_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: church_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  wamsjs:
    build:
      context: ./frontend/composeApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
